spring:
  profiles:
    active:
      - db
  application:
    name: 331-backend
  datasource:
    url: jdbc:mysql://localhost:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB

supabase:
  storage:
    endpoint: https://ilelidjqskinlqjxucuy.storage.supabase.co/storage/v1/s3
    endpoint_output: https://ilelidjqskinlqjxucuy.storage.supabase.co/storage/v1/object/public
    bucket: test
    region: us-east-2
    accessKey: 77212128a8cd38a08baddbd56408e0fd
    secretKey: 048ce46b95bd79bdac0648b9b3782381a76beb00c93b045d8ba78741744f7e97